# Tell tmux to use full 256-color mode and pass through true color
#set -g default-command "${SHELL} -i"

run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g mouse on
