# Tell tmux to use full 256-color mode and pass through true color
#set -g default-command "${SHELL} -i"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g mouse on

bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

bind | split-window -h
bind _ split-window -v

bind s switch-client -T split_keys
bind -T split_keys v split-window -h
bind -T split_keys h split-window -v
bind -T split_keys w choose-session

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'
